improved reporting of errors

diff --git a/.github/workflows/check_project_tags.yml b/.github/workflows/check_project_tags.yml
--- a/.github/workflows/check_project_tags.yml
+++ b/.github/workflows/check_project_tags.yml
@@ -18,13 +18,15 @@ jobs:
         uses: actions/checkout@v2
       - name: "Check all files for DiscoPoP License tag"
         run: |
-          ERROR=0
+          ERROR_FILES=""
           for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**")
           do
-            head -n 20 ${FILE} | grep -q "DiscoPoP software" || echo "Missing License tag at: ${FILE}" || ERROR=1
-            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" || ERROR=1
-            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" || ERROR=1
+            ERROR=""
+            head -n 20 ${FILE} | grep -q "DiscoPoP software" || echo "Missing License tag at: ${FILE}" || ERROR="yes"
+            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" || ERROR="yes"
+            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" || ERROR="yes"
+            # add file to ERROR_FILES if the license tag is missing
+            [ -z "$ERROR" ] && ERROR_FILES="${ERROR_FILES};${FILE}"
           done
-          exit $ERROR
-
-        # head -n 20 setup.py | grep "DiscoPoP software\|\|3-Clause BSD License"
+          # Report missing license tags
+          [ -z "$ERROR_FILES" ] && echo "Error files:\n${ERROR_FILES}" && exit 1
