added check for license string

diff --git a/.github/workflows/check_project_tags.yml b/.github/workflows/check_project_tags.yml
--- a/.github/workflows/check_project_tags.yml
+++ b/.github/workflows/check_project_tags.yml
@@ -18,10 +18,13 @@ jobs:
         uses: actions/checkout@v2
       - name: "Check all files for DiscoPoP License tag"
         run: |
+          ERROR=0
           for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**")
           do
-            echo "Hello from: ${FILE}"
+            head -n 20 ${FILE} | grep "DiscoPoP software" || echo "Missing License tag at: ${FILE}" || ERROR=1
+            head -n 20 ${FILE} | grep "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" || ERROR=1
+            head -n 20 ${FILE} | grep "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" || ERROR=1
           done
-          exit 1
+          exit $ERROR
 
-        # head -n 20 setup.py | grep "DiscoPoP software\|Technische Universitaet Darmstadt, Germany\|3-Clause BSD License"
+        # head -n 20 setup.py | grep "DiscoPoP software\|\|3-Clause BSD License"
