.

diff --git a/.github/workflows/check_project_tags.yml b/.github/workflows/check_project_tags.yml
--- a/.github/workflows/check_project_tags.yml
+++ b/.github/workflows/check_project_tags.yml
@@ -18,18 +18,17 @@ jobs:
         uses: actions/checkout@v2
       - name: "Check all files for DiscoPoP License tag"
         run: |
-          ERROR_FILES=""
+          ERROR=""
           for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**")
           do
-            ERROR=""
-            head -n 20 ${FILE} | grep -q "DiscoPoP software" || ERROR="yes"
-            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || ERROR="yes"
-            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || ERROR="yes"
-            # add file to ERROR_FILES if the license tag is missing
-            [ -z "$ERROR" ] && ERROR_FILES="${ERROR_FILES};${FILE}"
+            FILE_ERROR=""
+            head -n 20 ${FILE} | grep -q "DiscoPoP software" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
+            [-z "$FILE_ERROR"] || continue
+            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
+            [-z "$FILE_ERROR"] || continue
+            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" && FILE_ERROR="yes" && ERROR="yes"
           done
-          # Report missing license tags, if ERROR_FILES is not empty
-          [ -z "$ERROR_FILES" ] && exit 0
-
-          echo "Error files:\n${ERROR_FILES}" 
-          exit 1
+          # Report error (1), if license tags are missing
+          [ -z "$ERROR" ] || exit 1
+          # else, finish without error
+          exit 0
