.

diff --git a/.github/workflows/check_project_tags.yml b/.github/workflows/check_project_tags.yml
--- a/.github/workflows/check_project_tags.yml
+++ b/.github/workflows/check_project_tags.yml
@@ -18,16 +18,18 @@ jobs:
         uses: actions/checkout@v2
       - name: "Check all files for DiscoPoP License tag"
         run: |
-          ERROR=""
+          ERROR_FILES=""
           for FILE in $(find . -type f -not -path "**/.git/**" -not -path "**/test/**")
           do
-            head -n 20 ${FILE} | grep -q "DiscoPoP software" || echo "Missing License tag at: ${FILE}" && ERROR="yes"
-            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || echo "Missing License tag at: ${FILE}" && ERROR="yes"
-            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || echo "Missing License tag at: ${FILE}" && ERROR="yes"
+            ERROR=""
+            head -n 20 ${FILE} | grep -q "DiscoPoP software" || ERROR="yes"
+            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || ERROR="yes"
+            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || ERROR="yes"
+            # add file to ERROR_FILES if the license tag is missing
+            [ -z "$ERROR" ] && ERROR_FILES="${ERROR_FILES};${FILE}"
           done
-          if [ -z "$ERROR" ]
-          then
-                exit 0
-          else
-                exit 1
-          fi
+          # Report missing license tags, if ERROR_FILES is not empty
+          [ -z "$ERROR_FILES" ] && exit 0
+
+          echo "Error files:\n${ERROR_FILES}" 
+          exit 1
