First step towards Release 2.0.0 (#180)
* cleanup: removed old comments, fixed indentations and code formatting

* cleanup: added DiscoPoP project tag to files

* cleanup: unified header file extensions

* cleanup: added pragma once to DiscoPoP header files

* feature: added wiki pages

* cleanup: added and modified CI structure for more useful results

* feature: combined all passes into the single DiscoPoP optimizer pass

* feature: added DiscoPoP Configuration Wizard

* feature: added DiscoPoP Execution Wizard (runDiscoPoP script)

* fix: missing reporting of reductions, do-all's and pipelines in suggestions

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -9,166 +9,160 @@
 name: "DiscoPoP CI"
 on: [push, pull_request]
 
-jobs:
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
 
-  discopop_explorer:
-    name: "Explorer"
-    runs-on: ubuntu-20.04
-    strategy:
-      matrix:
-        python-version: [ 3.6 ]
+jobs:
+  execute_tests:
+    runs-on: ubuntu-latest
+    name: Execute CI Tests
     steps:
-      - name: "Checkout Repository"
+      - name: Checkout Repository
         uses: actions/checkout@v2
+
+      - name: "Check all files for DiscoPoP License tag"
+        run: |
+          ERROR=""
+          for FILE in $(find . -type f  -not -path "**/.git/**" -not -path "**/test/**" \
+                                        -not -path "**/docs/**" \
+                                        -not -path "**/LICENSE" -not -path "./VERSION" \
+                                        -not -path "**/_version.py" -not -path "**/__init__.py" \
+                                        -not -path "**.png" -not -path "**.svg" \
+                                        )
+          do
+            FILE_ERROR=""
+            head -n 20 ${FILE} | grep -q "DiscoPoP software" || FILE_ERROR="yes"
+            [ -z "$FILE_ERROR" ] || ERROR="yes"
+            [ -z "$FILE_ERROR" ] || echo "Missing License tag at: ${FILE}" 
+            [ -z "$FILE_ERROR" ] || continue
+            head -n 20 ${FILE} | grep -q "Technische Universitaet Darmstadt, Germany" || FILE_ERROR="yes"
+            [ -z "$FILE_ERROR" ] || ERROR="yes"
+            [ -z "$FILE_ERROR" ] || echo "Missing License tag at: ${FILE}" 
+            [ -z "$FILE_ERROR" ] || continue
+            head -n 20 ${FILE} | grep -q "3-Clause BSD License" || FILE_ERROR="yes"
+            [ -z "$FILE_ERROR" ] || ERROR="yes"
+            [ -z "$FILE_ERROR" ] || echo "Missing License tag at: ${FILE}" 
+          done
+          # Report error (1), if license tags are missing
+          [ -z "$ERROR" ] || exit 1
+
       - name: Setup Python
         uses: actions/setup-python@v2
         with:
-          python-version: ${{ matrix.python-version }}
-      - name: "Install Dependencies"
+          python-version: 3.6
+
+      - name: Install Python dependencies
         run: |
           python -m pip install -r discopop_explorer/requirements.txt
+          python -m pip install -r discopop_profiler/requirements.txt
           python -m pip install mypy data-science-types black
-      - name: "Run tests"
+
+      - name: Python Unit-tests
         run: python -m unittest -v
-      - name: "Run MyPy Type Checker"
-        run: python -m mypy -p discopop_explorer -p discopop_profiler
-      - name: "Check formatting of discopop_profiler"
+
+      - name: "Run MyPy Type Checker - DiscoPoP Explorer"
+        run: python -m mypy -p discopop_explorer
+
+      - name: "Run MyPy Type Checker - DiscoPoP Profiler"
+        run: python -m mypy -p discopop_profiler
+
+      - name: "Check formatting of DiscoPoP Explorer"
+        run: python -m black -l 100 --check discopop_explorer
+
+      - name: "Check formatting of DiscoPoP Profiler"
         run: python -m black -l 100 --check discopop_profiler
 
-  discopop_profiler:
-    name: "Profiler"
-    runs-on: ubuntu-20.04
-    steps:
-      - name: "Checkout Repository"
-        uses: actions/checkout@v2
-      - name: "Install Dependencies"
+      - name: Test DiscoPop Explorer
         run: |
+          TARGETS="mergesort reduction simple_pipeline"
+          PATTERNS="do_all reduction"
+          for target in $TARGETS; do
+            echo "checking target: ${target}"
+            python -m discopop_explorer --path=test/${target}/data --json=test/${target}/data/result_${target}.json
+            # count different suggestions and check against test data
+            for pattern in $PATTERNS; do
+              echo "checking pattern: ${pattern}"
+              ACTUAL=$(echo "$(cat test/${target}/data/result_${target}.json | python3 -c "import sys, json; print(json.load(sys.stdin)['${pattern}'])" | grep -c "node_id")")
+              EXPECTED=$(echo "$(cat test/${target}.json | python3 -c "import sys, json; print(json.load(sys.stdin)['${pattern}'])" | grep -c "node_id")")
+              if [ "$ACTUAL" != "$EXPECTED" ]; then
+                echo "::error:: ${pattern}: Amount of mentioned node ids in identified suggestions not equal! Expected: $EXPECTED, Actual: ${ACTUAL}"
+                exit 1
+              fi
+            done
+            echo ""
+          done
+
+      - name: Setup DiscoPoP Profiler - Install Dependencies
+        run: |
+          sudo apt-get update
           sudo apt-get remove clang-8 clang-10 clang-9 clang-12 clang-11
           wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
           sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
           sudo apt-get update
-          sudo apt-get install libclang-11-dev clang-11 llvm-11
-      - name: "Build DiscoPoP Profiler"
+          sudo apt-get install -y cmake libclang-11-dev clang-11 llvm-11
+          sudo ln -s /usr/bin/clang-11 /usr/bin/clang || true
+          sudo ln -s /usr/bin/clang++-11 /usr/bin/clang++ || true
+          sudo ln -s /usr/bin/llvm-link-11 /usr/bin/llvm-link || true
+          sudo ln -s /usr/bin/opt-11 /usr/bin/opt || true
+
+      - name: "Setup DiscoPoP Profiler - Build"
         run: |
           mkdir build
           cd build
           cmake -DCMAKE_BUILD_TYPE=Debug ..
           make -j3
-      - name: "Setup Python"
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.6
-      - name: "Run DiscoPoP Profiler on test/ Targets"
-        run: |
-          chmod +x .github/workflows/discopop_profiler/test.sh
-          .github/workflows/discopop_profiler/test.sh
 
-#  differential_test_llvm_8_vs_11:
-#    name: "Differential test: LLVM 8 vs. 11"
-#    runs-on: ubuntu-20.04
-#    steps:
-#      - name: "Checkout Repository"
-#        uses: actions/checkout@v2
-#      - name: "Install cmake"
-#        run: |
-#          sudo apt-get update
-#          sudo apt-get install -y cmake
-#      - name: "Install LLVM 11"
-#        run: |
-#          sudo apt-get remove clang-8 clang-10 clang-9 clang-12 clang-11
-#          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
-#          sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-11 main"
-#          sudo apt-get update
-#          sudo apt-get install -y libclang-11-dev clang-11 llvm-11
-#          sudo ln -s /usr/bin/clang-11 /usr/bin/clang || true
-#          sudo ln -s /usr/bin/clang++-11 /usr/bin/clang++ || true
-#          sudo ln -s /usr/bin/llvm-link-11 /usr/bin/llvm-link || true
-#          sudo ln -s /usr/bin/opt-11 /usr/bin/opt || true
-#      - name: "Build DiscoPoP Profiler"
-#        run: |
-#          mkdir build
-#          cd build
-#          cmake -DCMAKE_BUILD_TYPE=Debug ..
-#          make -j3
-#      - name: "Create Filemapping"
-#        run: |
-#          cp scripts/dp-fmap test/differential_mergesort
-#          cd test/differential_mergesort
-#          ./dp-fmap
-#      - name: "Execute DiscoPoP using LLVM 11"
-#        run: |
-#          cd test/differential_mergesort
-#          ./execute_dp.sh
-#      - name: "Store Results: LLVM 11"
-#        run: |
-#          mkdir ../dp_output_llvm_11
-#          mv test/differential_mergesort/out_dep.txt ../dp_output_llvm_11
-#          mv test/differential_mergesort/Data.xml ../dp_output_llvm_11
-#          mv test/differential_mergesort/loop_counter_output.txt ../dp_output_llvm_11
-#          mv test/differential_mergesort/reduction.txt ../dp_output_llvm_11
-#      - name: "Cleanup"
-#        run: |
-#          cd test/differential_mergesort
-#          rm *.txt
-#          rm out
-#      - name: "Install LLVM 8"
-#        run: |
-#          sudo apt-get remove -y clang-10 clang-9 clang-12 clang-11
-#          sudo apt-get install -y libclang-8-dev clang-8 llvm-8
-#          sudo rm /usr/bin/clang
-#          sudo rm /usr/bin/clang++
-#          sudo rm /usr/bin/llvm-link
-#          sudo rm /usr/bin/opt
-#          sudo ln -s /usr/bin/clang-8 /usr/bin/clang
-#          sudo ln -s /usr/bin/clang++-8 /usr/bin/clang++
-#          sudo ln -s /usr/bin/llvm-link-8 /usr/bin/llvm-link
-#          sudo ln -s /usr/bin/opt-8 /usr/bin/opt
-#      - name: "Remove DiscoPoP build folder created using LLVM 11"
-#        run: rm -r build
-#      - name: "Checkout Repository"
-#        uses: actions/checkout@v2
-#      - name: "Checkout commit using LLVM 8"
-#        run: |
-#          git fetch
-#          git checkout c005800d4a44df2c39446786fb8ecb1841308e5a
-#      - name: "Build DiscoPoP Profiler"
-#        run: |
-#          mkdir build
-#          cd build
-#          cmake -DCMAKE_BUILD_TYPE=Debug ..
-#          make -j3
-#      - name: "Create Filemapping"
-#        run: |
-#          cp scripts/dp-fmap test/differential_mergesort
-#          cd test/differential_mergesort
-#          ./dp-fmap
-#      - name: "Execute DiscoPoP using LLVM 8"
-#        run: |
-#          cd test/differential_mergesort
-#          ./execute_dp.sh
-#      - name: "Store Results: LLVM 8"
-#        run: |
-#          mkdir ../dp_output_llvm_8
-#          mv test/differential_mergesort/out_dep.txt ../dp_output_llvm_8
-#          mv test/differential_mergesort/Data.xml ../dp_output_llvm_8
-#          mv test/differential_mergesort/loop_counter_output.txt ../dp_output_llvm_8
-#          mv test/differential_mergesort/reduction.txt ../dp_output_llvm_8
-#      - name: "Sort results for sake of comparability"
-#        run: |
-#          sort ../dp_output_llvm_11/loop_counter_output.txt >> ../dp_output_llvm_11/loop_counter_output.sorted
-#          sort ../dp_output_llvm_11/Data.xml >> ../dp_output_llvm_11/Data.sorted
-#          sort ../dp_output_llvm_11/reduction.txt >> ../dp_output_llvm_11/reduction.sorted
-#          sort ../dp_output_llvm_11/out_dep.txt >> ../dp_output_llvm_11/out_dep.sorted
-#          sort ../dp_output_llvm_8/loop_counter_output.txt >> ../dp_output_llvm_8/loop_counter_output.sorted
-#          sort ../dp_output_llvm_8/Data.xml >> ../dp_output_llvm_8/Data.sorted
-#          sort ../dp_output_llvm_8/reduction.txt >> ../dp_output_llvm_8/reduction.sorted
-#          sort ../dp_output_llvm_8/out_dep.txt >> ../dp_output_llvm_8/out_dep.sorted
-#
-#      - name: "Compare results"
-#        run: |
-#          # || used for error handling
-#          cmp ../dp_output_llvm_11/loop_counter_output.sorted ../dp_output_llvm_8/loop_counter_output.sorted || diff ../dp_output_llvm_11/loop_counter_output.sorted ../dp_output_llvm_8/loop_counter_output.sorted
-#          cmp ../dp_output_llvm_11/Data.sorted ../dp_output_llvm_8/Data.sorted || diff ../dp_output_llvm_11/Data.sorted ../dp_output_llvm_8/Data.sorted
-#          cmp ../dp_output_llvm_11/reduction.sorted ../dp_output_llvm_8/reduction.sorted || diff ../dp_output_llvm_11/reduction.sorted ../dp_output_llvm_8/reduction.sorted
-#          cmp ../dp_output_llvm_11/out_dep.sorted ../dp_output_llvm_8/out_dep.sorted || diff ../dp_output_llvm_11/out_dep.sorted ../dp_output_llvm_8/out_dep.sorted
-#
+      - name: "Setup DiscoPoP Profiler - Create executable"
+        run: chmod +x .github/workflows/tests/profiler.sh
+
+      - name: "Execute DiscoPoP Profiler - mergesort - discopopPass"
+        run: .github/workflows/tests/profiler.sh mergesort discopopPass
+
+      - name: "Execute DiscoPoP Profiler - reduction - discopopPass"
+        run: .github/workflows/tests/profiler.sh reduction discopopPass
+
+      - name: "Execute DiscoPoP Profiler - simple_pipeline - discopopPass"
+        run: .github/workflows/tests/profiler.sh simple_pipeline discopopPass
+
+  ci_successful:
+    name: "CI Tests Successful"
+    runs-on: ubuntu-latest
+    needs: execute_tests
+    steps:
+      - name: "Report success"
+        run: exit 0
+
+
+  update_wiki-build:
+    name: "Update Wiki - Build"
+    runs-on: ubuntu-latest
+    needs: ci_successful
+    if: github.ref == 'refs/heads/master'
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Setup Pages
+        uses: actions/configure-pages@v2
+      - name: Build with Jekyll
+        uses: actions/jekyll-build-pages@v1
+        with:
+          source: ./docs/
+          destination: ./_site
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v1
+
+  update_wiki-deploy:
+    name: "Update Wiki - Deploy"
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: update_wiki-build
+    if: github.ref == 'refs/heads/master'
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v1
